import { AuctionItem, Item, SellerApplication, User } from './types';

// Mock Users Data
export const users: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2023-01-15'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'seller',
    status: 'active',
    createdAt: new Date('2023-02-20'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: '3',
    name: 'Michael Johnson',
    email: 'michael@example.com',
    role: 'seller',
    status: 'pending',
    createdAt: new Date('2023-03-10'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '4',
    name: 'Emily Wilson',
    email: 'emily@example.com',
    role: 'buyer',
    status: 'active',
    createdAt: new Date('2023-02-05'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'David Brown',
    email: 'david@example.com',
    role: 'buyer',
    status: 'inactive',
    createdAt: new Date('2023-01-30'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: '6',
    name: 'Sophia Miller',
    email: 'sophia@example.com',
    role: 'seller',
    status: 'active',
    createdAt: new Date('2023-03-22'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: '7',
    name: 'James Anderson',
    email: 'james@example.com',
    role: 'buyer',
    status: 'active',
    createdAt: new Date('2023-02-15'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: '8',
    name: 'Olivia Taylor',
    email: 'olivia@example.com',
    role: 'seller',
    status: 'pending',
    createdAt: new Date('2023-03-05'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
];

// Mock Items Data
export const items: Item[] = [
  {
    id: '1',
    name: 'Vintage Watch',
    description: 'A beautiful vintage watch from the 1950s',
    price: 1250,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'approved',
    category: 'Watches',
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d',
    createdAt: new Date('2023-02-25'),
  },
  {
    id: '2',
    name: 'Antique Vase',
    description: 'Handcrafted ceramic vase from the 19th century',
    price: 850,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'pending',
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1612196808214-b7e9e1cbf686',
    createdAt: new Date('2023-03-02'),
  },
  {
    id: '3',
    name: 'Oil Painting',
    description: 'Original oil painting of a countryside landscape',
    price: 3500,
    sellerId: '6',
    sellerName: 'Sophia Miller',
    status: 'approved',
    category: 'Art',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119',
    createdAt: new Date('2023-02-10'),
  },
  {
    id: '4',
    name: 'Diamond Necklace',
    description: 'Elegant diamond necklace with white gold chain',
    price: 12000,
    sellerId: '6',
    sellerName: 'Sophia Miller',
    status: 'rejected',
    category: 'Jewelry',
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0',
    createdAt: new Date('2023-03-15'),
  },
  {
    id: '5',
    name: 'Rare Book Collection',
    description: 'Collection of first-edition classic novels',
    price: 5000,
    sellerId: '3',
    sellerName: 'Michael Johnson',
    status: 'pending',
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18',
    createdAt: new Date('2023-03-20'),
  },
  {
    id: '6',
    name: 'Vintage Car',
    description: 'Restored 1965 Ford Mustang in excellent condition',
    price: 75000,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'approved',
    category: 'Vehicles',
    imageUrl: 'https://images.unsplash.com/photo-1533559662856-75d61c18f8da',
    createdAt: new Date('2023-01-28'),
  },
];

// Mock Seller Applications Data
export const sellerApplications: SellerApplication[] = [
  {
    id: '1',
    userId: '3',
    firstName: 'Michael',
    lastName: 'Johnson',
    username: 'michael_j',
    email: 'michael@example.com',
    category: 'Paintings',
    background: 'I have been collecting and selling art for over 10 years and would like to expand my business to your platform. I specialize in contemporary paintings and work with several local artists to promote their work.',
    status: 'pending',
    submittedAt: new Date('2023-03-08'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '2',
    userId: '8',
    firstName: 'Olivia',
    lastName: 'Taylor',
    username: 'olivia_t',
    email: 'olivia@example.com',
    category: 'Sculptures',
    background: 'I am a sculptor with 8 years of experience creating and selling unique pieces. I work primarily with clay and bronze, and I\'m excited about the possibility of reaching a wider audience through your platform.',
    status: 'pending',
    submittedAt: new Date('2023-03-01'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: '3',
    userId: '4',
    firstName: 'Emily',
    lastName: 'Wilson',
    username: 'emily_w',
    email: 'emily@example.com',
    category: 'Mixed Media',
    background: 'I\'ve been running a small art gallery for 5 years, featuring works from various local artists. We specialize in mixed media pieces that combine traditional and digital techniques, and I believe your platform would be perfect for expanding our reach.',
    status: 'approved',
    submittedAt: new Date('2023-02-20'),
    avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '4',
    userId: '7',
    firstName: 'James',
    lastName: 'Anderson',
    username: 'james_a',
    email: 'james@example.com',
    category: 'Photography',
    background: 'I am a professional photographer with 12 years of experience in fine art photography. My work has been featured in several galleries, and I\'m looking to expand my online presence through your auction platform.',
    status: 'rejected',
    submittedAt: new Date('2023-02-15'),
    avatarUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
];

// Mock Auction Items Data
export const auctionItems: AuctionItem[] = [
  {
    id: '1',
    name: 'Vintage Watch',
    description: 'A beautiful vintage watch from the 1950s',
    price: 1250,
    startingBid: 1000,
    currentBid: 1750,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'approved',
    category: 'Watches',
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d',
    createdAt: new Date('2023-02-25'),
    auctionStart: new Date('2023-03-15'),
    auctionEnd: new Date('2023-03-25'),
  },
  {
    id: '3',
    name: 'Oil Painting',
    description: 'Original oil painting of a countryside landscape',
    price: 3500,
    startingBid: 3000,
    currentBid: 3200,
    sellerId: '6',
    sellerName: 'Sophia Miller',
    status: 'approved',
    category: 'Art',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119',
    createdAt: new Date('2023-02-10'),
    auctionStart: new Date('2023-03-10'),
    auctionEnd: new Date('2023-03-20'),
  },
  {
    id: '2',
    name: 'Antique Vase',
    description: 'Handcrafted ceramic vase from the 19th century',
    price: 850,
    startingBid: 800,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'pending',
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1612196808214-b7e9e1cbf686',
    createdAt: new Date('2023-03-02'),
  },
  {
    id: '5',
    name: 'Rare Book Collection',
    description: 'Collection of first-edition classic novels',
    price: 5000,
    startingBid: 4500,
    sellerId: '3',
    sellerName: 'Michael Johnson',
    status: 'pending',
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18',
    createdAt: new Date('2023-03-20'),
  },
  {
    id: '6',
    name: 'Vintage Car',
    description: 'Restored 1965 Ford Mustang in excellent condition',
    price: 75000,
    startingBid: 70000,
    currentBid: 72500,
    sellerId: '2',
    sellerName: 'Jane Smith',
    status: 'approved',
    category: 'Vehicles',
    imageUrl: 'https://images.unsplash.com/photo-1533559662856-75d61c18f8da',
    createdAt: new Date('2023-01-28'),
    auctionStart: new Date('2023-02-15'),
    auctionEnd: new Date('2023-03-30'),
  },
];
